version: '3.4'

services:
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: <changeme>
      MYSQL_DATABASE: htb
      MYSQL_USER: htb
      MYSQL_PASSWORD: <changeme>
    restart: always
    ports:
      - 127.0.0.1:3306:3306
  htbupdatesdiscordbot:
    image: htbupdatesdiscordbot
    build:
      context: .
      dockerfile: HTB Updates Discord Bot/Dockerfile
    restart: always
  htbupdatesfrontend:
    image: htbupdatesfrontend
    build:
      context: .
      dockerfile: htb_updates_frontend/Dockerfile
    ports:
      - 127.0.0.1:8000:80
    restart: always
  htbupdatesbackend:
    image: htbupdatesbackend
    build:
      context: .
      dockerfile: htb_updates_backend/Dockerfile
    restart: always
